In [ ]:
from ingestion import riot_api_functions as riot
r = riot.get_match_id_list(division="DIAMOND", tier="I")
print(r)

Rate limit exceeded. Retrying after 66 seconds
Rate limit reached (100/120s). Waiting for 9.25 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 65.45 seconds before making more requests
Rate limit reached (100/120s). Waiting for 9.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 65.52 seconds before making more requests
Rate limit reached (100/120s). Waiting for 9.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 65.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 9.00 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 64.81 seconds before making more requests
Rate limit reached (100/120s). Waiting for 8.89 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 64.69 seconds before making more requests
Rate limit reached (100/120s). Waiting for 8.67 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.27 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 64.92 seconds before making more requests
Rate limit reached (100/120s). Waiting for 8.53 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.30 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 65.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 8.47 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.20 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 65.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 8.42 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.23 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 65.36 seconds before making more requests
Rate limit reached (100/120s). Waiting for 8.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests

In [ ]:
import sqlite3
connection = sqlite3.connect('metadata/pipelines.db')
cursor = connection.cursor()
r = cursor.execute('SELECT * FROM summoners_handling')
print(r.fetchall())
r = cursor.execute('DELETE FROM summoners_handling')
connection.commit()

r= cursor.execute('INSERT INTO summoners_handling (summoner_puuid, last_request_time) VALUES (?, ?)', ('yZ5DVaKStyXKVPbGsG6G41Cm8zJZ52pR6LvYuEVC-IvYk58n7gt_HYtftrjiPrlHWMRlICik58njfA', '2026-07-01 00:00:00'))
connection.commit()
cursor.close()

[('yZ5DVaKStyXKVPbGsG6G41Cm8zJZ52pR6LvYuEVC-IvYk58n7gt_HYtftrjiPrlHWMRlICik58njfA', '2026-07-01 00:00:00', None)]

In [3]:
import sqlite3
from datetime import datetime, timedelta
from metadata import metadata

last_request_time, downloaded = metadata.check_last_oracle_elixir_requested(year=2026)
last_week = datetime.now() - timedelta(weeks=1)
print(f"Last request time: {last_request_time}, Last week: {last_week.isoformat()}")
x = last_request_time > last_week.isoformat()
print(x)

Last request time: 2026-07-21T08:25:44.027563, Last week: 2026-07-14T08:28:08.348192
True

In [2]:
from ingestion import riot_api_functions as riot
r = riot.process_match_list()
print(r)

Rate limit reached (100/120s). Waiting for 56.97 seconds before making more requests
Rate limit reached (100/120s). Waiting for 52.30 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.25 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.28 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.33 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.25 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.33 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.47 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.45 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.33 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 52.53 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.30 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.27 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.72 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.39 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.44 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.23 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 52.73 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.33 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.81 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.33 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.24 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.31 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.39 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 52.56 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.38 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.78 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.34 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.34 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.39 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 52.67 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.30 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.27 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.28 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.73 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.27 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.31 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.31 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.17 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.20 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.20 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.44 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.20 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.22 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.34 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.11 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.23 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.31 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.09 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.01 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.02 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.03 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.08 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.05 seconds before making more requests
Rate limit reached (100/120s). Waiting for 52.80 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.12 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.31 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.19 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.06 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.16 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.83 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.14 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.44 seconds before making more requests
Rate limit reached (100/120s). Waiting for 0.33 seconds before making more requests

In [1]:
from ingestion import oe_functions as oe
r = oe.download_oe_data()
print(r)

Retrieving folder contents

Processing file 12syQsRH2QnKrQZTQQ6G5zyVeTG2pAYvu 2014_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1qyckLuw0-hJM8XqFhlV9l1xAbr3H78T_ 2015_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1muyfpaIqk8_0BFkgLCWXDGNgWSXoPBwG 2016_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 11fx3nNjSYB0X8vKxLAbYOrS2Bu6avm9A 2017_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1GsNetJQOMx0QJ6_FN8M1kwGvU_GPPcPZ 2018_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 11eKtScnZcpfZcD3w3UrD7nnpfLHvj9_t 2019_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1dlSIczXShnv1vIfGNvBjgk-thMKA5j7d 2020_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1fzwTTz77hcnYjOnO9ONeoPrkWCoOSecA 2021_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1EHmptHyzY8owv0BAcNKtkQpMwfkURwRy 2022_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1XXk2LO0CsNADBB1LRGOV5rUpyZdEZ8s2 2023_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1IjIEhLc9n8eLKeY-yh_YigKVWbhgGBsN 2024_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1v6LRphp2kYciU4SXp0PCjEMuev1bDejc 2025_LoL_esports_match_data_from_OraclesElixir.csv
Processing file 1hnpbrUpBMS1TZI7IovfpKeZfWJH1Aptm 2026_LoL_esports_match_data_from_OraclesElixir.csv

Retrieving folder contents completed
Building directory structure
Building directory structure completed

Error downloading from Google Drive: Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=12syQsRH2QnKrQZTQQ6G5zyVeTG2pAYvu

but Gdown can't. Please check connections and permissions.
False

In [1]:
import sqlite3
import os
import pandas as pd
from metadata import metadata
connection = sqlite3.connect('metadata/pipelines.db')
cursor = connection.cursor()

# patch_csv = pd.read_csv('datasets/bronze/patches/scraped_patch_notes.csv')

# for index, row in patch_csv.iterrows():
#     patch_version = row['patch_number']
#     metadata.log_patch_notes_request(patch_version)

r = metadata.get_last_patch_notes_requested()
print(r)

# cursor.execute('UPDATE patch_notes_handling set patch_version = "25" where patch_version = "2025.0"')
# connection.commit()

# cursor.execute("""
# SELECT patch_version, CAST(substr(patch_version, 1, instr(patch_version, '.') - 1) AS INTEGER) AS major_version,
#        CAST(substr(patch_version, instr(patch_version, '.') + 1) AS INTEGER) AS minor_version
# FROM patch_notes_handling
# ORDER BY
#   CAST(substr(patch_version, 1, instr(patch_version, '.') - 1) AS INTEGER) DESC,
#   CAST(substr(patch_version, instr(patch_version, '.') + 1) AS INTEGER) DESC
# """)
# result = cursor.fetchall()
# print(result)

26.13

In [1]:
from ingestion import patch_scraping_functions as psf
r = psf.get_new_patch_notes()
print(r)

Processing patch version: 9.1
Processing patch version: 9.2
Processing patch version: 9.3
Processing patch version: 9.18
Processing patch version: 9.19
Processing patch version: 9.20
Processing patch version: 9.21
Processing patch version: 9.22
Processing patch version: 9.23
Processing patch version: 9.24
Downloaded image
Downloaded image for patch 9.24: 9.24_patch_highlights.jpg
Processing patch version: 10.1
Processing patch version: 10.2
Processing patch version: 10.3
Processing patch version: 10.4
Processing patch version: 10.5
Processing patch version: 10.6
Processing patch version: 10.7
Processing patch version: 10.8
Processing patch version: 10.9
Processing patch version: 10.10
Downloaded image
Downloaded image for patch 10.10: 10.10_patch_highlights.png
Extracted changes for patch 10.10: [{'champion': 'Annie', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Irelia', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Nidalee', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Sivir', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Soraka', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Twisted Fate', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Udyr', 'change_type': 'Buff', 'patch_number': '10.10'}, {'champion': 'Diana', 'change_type': 'Nerf', 'patch_number': '10.10'}, {'champion': 'Katarina', 'change_type': 'Nerf', 'patch_number': '10.10'}, {'champion': 'Kayn', 'change_type': 'Nerf', 'patch_number': '10.10'}, {'champion': 'Kled', 'change_type': 'Nerf', 'patch_number': '10.10'}, {'champion': 'Miss Fortune', 'change_type': 'Nerf', 'patch_number': '10.10'}, {'champion': 'Maokai', 'change_type': 'Nerf', 'patch_number': '10.10'}, {'champion': 'Taric', 'change_type': 'Nerf', 'patch_number': '10.10'}]
Saved changes to CSV for patch 10.10
Processing patch version: 10.11
Downloaded image
Downloaded image for patch 10.11: 10.11_patch_highlights.jpg
Extracted changes for patch 10.11: [{'champion': 'Fiddlesticks', 'change_type': 'Buff', 'patch_number': '10.11'}, {'champion': 'Gangplank', 'change_type': 'Buff', 'patch_number': '10.11'}, {'champion': 'Hecarim', 'change_type': 'Buff', 'patch_number': '10.11'}, {'champion': "Kai'Sa", 'change_type': 'Buff', 'patch_number': '10.11'}, {'champion': 'Lux', 'change_type': 'Buff', 'patch_number': '10.11'}, {'champion': 'Graves', 'change_type': 'Nerf', 'patch_number': '10.11'}, {'champion': 'Janna', 'change_type': 'Nerf', 'patch_number': '10.11'}, {'champion': 'Syndra', 'change_type': 'Nerf', 'patch_number': '10.11'}, {'champion': 'Talon', 'change_type': 'Nerf', 'patch_number': '10.11'}]
Saved changes to CSV for patch 10.11
Processing patch version: 10.12
Downloaded image
Downloaded image for patch 10.12: 10.12_patch_highlights.jpg
Extracted changes for patch 10.12: [{'champion': 'Akali', 'change_type': 'Buff', 'patch_number': '10.12'}, {'champion': 'Brand', 'change_type': 'Buff', 'patch_number': '10.12'}, {'champion': 'Senna', 'change_type': 'Buff', 'patch_number': '10.12'}, {'champion': 'Viktor', 'change_type': 'Buff', 'patch_number': '10.12'}, {'champion': 'Volibear', 'change_type': 'Buff', 'patch_number': '10.12'}, {'champion': 'Xayah', 'change_type': 'Buff', 'patch_number': '10.12'}, {'champion': 'Cassiopeia', 'change_type': 'Nerf', 'patch_number': '10.12'}, {'champion': 'Fiddlesticks', 'change_type': 'Nerf', 'patch_number': '10.12'}, {'champion': 'Trundle', 'change_type': 'Nerf', 'patch_number': '10.12'}, {'champion': 'Varus', 'change_type': 'Nerf', 'patch_number': '10.12'}, {'champion': 'Yasuo', 'change_type': 'Nerf', 'patch_number': '10.12'}]
Saved changes to CSV for patch 10.12
Processing patch version: 10.13
Downloaded image
Downloaded image for patch 10.13: 10.13_patch_highlights.png
Extracted changes for patch 10.13: [{'champion': 'Gnar', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': "Kog'Maw", 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Lucian', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Nocturne', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Nunu', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Rakan', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Ryze', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Vi', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Yorick', 'change_type': 'Buff', 'patch_number': '10.13'}, {'champion': 'Aphelios', 'change_type': 'Nerf', 'patch_number': '10.13'}, {'champion': 'Cassiopeia', 'change_type': 'Nerf', 'patch_number': '10.13'}, {'champion': 'Kalista', 'change_type': 'Nerf', 'patch_number': '10.13'}, {'champion': 'Ornn', 'change_type': 'Nerf', 'patch_number': '10.13'}, {'champion': 'Syndra', 'change_type': 'Nerf', 'patch_number': '10.13'}, {'champion': 'Yuumi', 'change_type': 'Nerf', 'patch_number': '10.13'}]
Saved changes to CSV for patch 10.13
Processing patch version: 10.14
Downloaded image
Downloaded image for patch 10.14: 10.14_patch_highlights.jpg
Extracted changes for patch 10.14: [{'champion': 'Alistar', 'change_type': 'Buff', 'patch_number': '10.14'}, {'champion': 'Karthus', 'change_type': 'Buff', 'patch_number': '10.14'}, {'champion': "Kha'Zix", 'change_type': 'Buff', 'patch_number': '10.14'}, {'champion': 'Riven', 'change_type': 'Buff', 'patch_number': '10.14'}, {'champion': 'Sejuani', 'change_type': 'Buff', 'patch_number': '10.14'}, {'champion': 'Zed', 'change_type': 'Buff', 'patch_number': '10.14'}, {'champion': 'Ezreal', 'change_type': 'Nerf', 'patch_number': '10.14'}, {'champion': 'Pyke', 'change_type': 'Nerf', 'patch_number': '10.14'}, {'champion': 'Trundle', 'change_type': 'Nerf', 'patch_number': '10.14'}, {'champion': 'Varus', 'change_type': 'Nerf', 'patch_number': '10.14'}, {'champion': 'Volibear', 'change_type': 'Nerf', 'patch_number': '10.14'}, {'champion': 'Wukong', 'change_type': 'Nerf', 'patch_number': '10.14'}]
Saved changes to CSV for patch 10.14
Processing patch version: 10.15
Downloaded image
Downloaded image for patch 10.15: 10.15_patch_highlights.jpg
Extracted changes for patch 10.15: [{'champion': 'Caitlyn', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Gragas', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Irelia', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Rakan', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Shen', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Skarner', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Swain', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Yuumi', 'change_type': 'Buff', 'patch_number': '10.15'}, {'champion': 'Aphelios', 'change_type': 'Nerf', 'patch_number': '10.15'}, {'champion': 'Fiddlesticks', 'change_type': 'Nerf', 'patch_number': '10.15'}, {'champion': 'Lee Sin', 'change_type': 'Nerf', 'patch_number': '10.15'}, {'champion': 'Ornn', 'change_type': 'Nerf', 'patch_number': '10.15'}, {'champion': 'Thresh', 'change_type': 'Nerf', 'patch_number': '10.15'}, {'champion': 'Twisted Fate', 'change_type': 'Nerf', 'patch_number': '10.15'}]
Saved changes to CSV for patch 10.15
Processing patch version: 10.16
Downloaded image
Downloaded image for patch 10.16: 10.16_patch_highlights.jpg
Extracted changes for patch 10.16: [{'champion': 'Ashe', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Bard', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Karma', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Karthus', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': "Kha'Zix", 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Nautilus', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Nocturne', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Sett', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Syndra', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Volibear', 'change_type': 'Nerf', 'patch_number': '10.16'}, {'champion': 'Akali', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Evelynn', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Fiora', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Hecarim', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Jax', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Jhin', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Jinx', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Lucian', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Miss Fortune', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Morgana', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Neeko', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Rakan', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Skarner', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Tristana', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Veigar', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Yasuo', 'change_type': 'Buff', 'patch_number': '10.16'}, {'champion': 'Ziggs', 'change_type': 'Buff', 'patch_number': '10.16'}]
Saved changes to CSV for patch 10.16
Processing patch version: 10.17
Downloaded image
Downloaded image for patch 10.17: 10.17_patch_highlights.png
Extracted changes for patch 10.17: [{'champion': 'Caitlyn', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Evelynn', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Hecarim', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Lux', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Qiyana', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Sona', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Yone', 'change_type': 'Nerf', 'patch_number': '10.17'}, {'champion': 'Aatrox', 'change_type': 'Buff', 'patch_number': '10.17'}, {'champion': 'Gragas', 'change_type': 'Buff', 'patch_number': '10.17'}, {'champion': "Kai'Sa", 'change_type': 'Buff', 'patch_number': '10.17'}, {'champion': 'Varus', 'change_type': 'Buff', 'patch_number': '10.17'}, {'champion': 'Xayah', 'change_type': 'Buff', 'patch_number': '10.17'}]
Saved changes to CSV for patch 10.17
Processing patch version: 10.18
Downloaded image
Downloaded image for patch 10.18: 10.18_patch_highlights.jpg
Extracted changes for patch 10.18: [{'champion': 'Ahri', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Jarvan IV', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Kayle', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Miss Fortune', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Rumble', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Twitch', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Xin Zhao', 'change_type': 'Buff', 'patch_number': '10.18'}, {'champion': 'Ashe', 'change_type': 'Nerf', 'patch_number': '10.18'}, {'champion': 'Galio', 'change_type': 'Nerf', 'patch_number': '10.18'}, {'champion': "Kog'Maw", 'change_type': 'Nerf', 'patch_number': '10.18'}, {'champion': 'Sett', 'change_type': 'Nerf', 'patch_number': '10.18'}, {'champion': 'Shen', 'change_type': 'Nerf', 'patch_number': '10.18'}]
Saved changes to CSV for patch 10.18
Processing patch version: 10.19
Downloaded image
Downloaded image for patch 10.19: 10.19_patch_highlights.png
Extracted changes for patch 10.19: [{'champion': 'Ahri', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Aphelios', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Irelia', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Ivern', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Sivir', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Sylas', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Udyr', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Vayne', 'change_type': 'Buff', 'patch_number': '10.19'}, {'champion': 'Akali', 'change_type': 'Nerf', 'patch_number': '10.19'}, {'champion': 'Azir', 'change_type': 'Nerf', 'patch_number': '10.19'}, {'champion': 'Caitlyn', 'change_type': 'Nerf', 'patch_number': '10.19'}, {'champion': 'Lucian', 'change_type': 'Nerf', 'patch_number': '10.19'}, {'champion': 'Senna', 'change_type': 'Nerf', 'patch_number': '10.19'}, {'champion': 'Twisted Fate', 'change_type': 'Nerf', 'patch_number': '10.19'}]
Saved changes to CSV for patch 10.19
Processing patch version: 10.20
Downloaded image
Downloaded image for patch 10.20: 10.20_patch_highlights.jpg
Extracted changes for patch 10.20: [{'champion': 'Aatrox', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Braum', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Illaoi', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Ryze', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Sion', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Urgot', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Varus', 'change_type': 'Buff', 'patch_number': '10.20'}, {'champion': 'Karthus', 'change_type': 'Nerf', 'patch_number': '10.20'}, {'champion': 'Kassadin', 'change_type': 'Nerf', 'patch_number': '10.20'}, {'champion': 'Katarina', 'change_type': 'Nerf', 'patch_number': '10.20'}, {'champion': 'Kled', 'change_type': 'Nerf', 'patch_number': '10.20'}, {'champion': 'Lulu', 'change_type': 'Nerf', 'patch_number': '10.20'}, {'champion': 'Maokai', 'change_type': 'Nerf', 'patch_number': '10.20'}, {'champion': 'Nunu', 'change_type': 'Nerf', 'patch_number': '10.20'}]
Saved changes to CSV for patch 10.20
Processing patch version: 10.21
Downloaded image
Downloaded image for patch 10.21: 10.21_patch_highlights.png
Extracted changes for patch 10.21: [{'champion': 'Aphelios', 'change_type': 'Buff', 'patch_number': '10.21'}, {'champion': 'Corki', 'change_type': 'Buff', 'patch_number': '10.21'}, {'champion': 'Karma', 'change_type': 'Buff', 'patch_number': '10.21'}, {'champion': 'Lee Sin', 'change_type': 'Buff', 'patch_number': '10.21'}, {'champion': 'Trundle', 'change_type': 'Buff', 'patch_number': '10.21'}, {'champion': 'Udyr', 'change_type': 'Buff', 'patch_number': '10.21'}, {'champion': 'Camille', 'change_type': 'Nerf', 'patch_number': '10.21'}, {'champion': 'Graves', 'change_type': 'Nerf', 'patch_number': '10.21'}, {'champion': 'Hecarim', 'change_type': 'Nerf', 'patch_number': '10.21'}, {'champion': 'Nidalee', 'change_type': 'Nerf', 'patch_number': '10.21'}, {'champion': 'Pantheon', 'change_type': 'Nerf', 'patch_number': '10.21'}, {'champion': 'Samira', 'change_type': 'Nerf', 'patch_number': '10.21'}]
Saved changes to CSV for patch 10.21
Processing patch version: 10.22
Downloaded image
Downloaded image for patch 10.22: 10.22_patch_highlights.png
Extracted changes for patch 10.22: [{'champion': 'Amumu', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'Annie', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'Brand', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'LeBlanc', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'Nasus', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'Sejuani', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'Xayah', 'change_type': 'Buff', 'patch_number': '10.22'}, {'champion': 'Karthus', 'change_type': 'Nerf', 'patch_number': '10.22'}, {'champion': 'Lulu', 'change_type': 'Nerf', 'patch_number': '10.22'}, {'champion': 'Samira', 'change_type': 'Nerf', 'patch_number': '10.22'}, {'champion': 'Zed', 'change_type': 'Nerf', 'patch_number': '10.22'}]
Saved changes to CSV for patch 10.22
Processing patch version: 10.23
Downloaded image
Downloaded image for patch 10.23: 10.23_patch_highlights.jpg
Processing patch version: 10.24
Downloaded image
Downloaded image for patch 10.24: 10.24_patch_highlights.jpg
Extracted changes for patch 10.24: [{'champion': 'Tryndamere', 'change_type': 'Buff', 'patch_number': '10.24'}, {'champion': 'Varus', 'change_type': 'Buff', 'patch_number': '10.24'}, {'champion': 'Amumu', 'change_type': 'Nerf', 'patch_number': '10.24'}, {'champion': 'Hecarim', 'change_type': 'Nerf', 'patch_number': '10.24'}, {'champion': 'Kayle', 'change_type': 'Nerf', 'patch_number': '10.24'}, {'champion': 'Samira', 'change_type': 'Nerf', 'patch_number': '10.24'}]
Saved changes to CSV for patch 10.24
Processing patch version: 10.25
Downloaded image
Downloaded image for patch 10.25: 10.25_patch_highlights.jpg
Extracted changes for patch 10.25: [{'champion': 'Annie', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Fizz', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Jhin', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Kayle', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Kayn', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Morgana', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Samira', 'change_type': 'Nerf', 'patch_number': '10.25'}, {'champion': 'Anivia', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Ekko', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Gragas', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Irelia', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Ivern', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Karthus', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Lee Sin', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Lulu', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Mordekaiser', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Nasus', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Nidalee', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Pantheon', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Seraphine', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Taliyah', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Twitch', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Yasuo', 'change_type': 'Buff', 'patch_number': '10.25'}, {'champion': 'Yone', 'change_type': 'Buff', 'patch_number': '10.25'}]
Saved changes to CSV for patch 10.25
Processing patch version: 11.1
Downloaded image
Downloaded image for patch 11.1: 11.1_patch_highlights.jpg
Extracted changes for patch 11.1: [{'champion': 'Gnar', 'change_type': 'Buff', 'patch_number': '11.1'}, {'champion': 'Karma', 'change_type': 'Buff', 'patch_number': '11.1'}, {'champion': 'Qiyana', 'change_type': 'Buff', 'patch_number': '11.1'}, {'champion': 'Ryze', 'change_type': 'Buff', 'patch_number': '11.1'}, {'champion': 'Xayah', 'change_type': 'Buff', 'patch_number': '11.1'}, {'champion': 'Fiddlesticks', 'change_type': 'Nerf', 'patch_number': '11.1'}, {'champion': 'Master Yi', 'change_type': 'Nerf', 'patch_number': '11.1'}, {'champion': 'Pantheon', 'change_type': 'Nerf', 'patch_number': '11.1'}]
Saved changes to CSV for patch 11.1
Processing patch version: 11.2
Downloaded image
Downloaded image for patch 11.2: 11.2_patch_highlights.jpg

In [2]:
import sqlite3
connection = sqlite3.connect('metadata/pipelines.db')
cursor = connection.cursor()
r = cursor.execute('SELECT * FROM patch_notes_handling ORDER BY last_request_time DESC')
print(r.fetchall())
# r = cursor.execute('DELETE FROM patch_notes_handling')
# connection.commit()

cursor.close()

[('2025', '2026-07-27T08:17:23.361435'), ('26.14', '2026-07-27T08:17:11.244720'), ('26.13', '2026-07-27T08:17:02.912619'), ('26.12', '2026-07-27T08:16:52.394772'), ('26.11', '2026-07-27T08:16:42.984546'), ('26.10', '2026-07-27T08:16:35.428477'), ('26.9', '2026-07-27T08:16:26.278237'), ('26.8', '2026-07-27T08:16:17.133474'), ('26.7', '2026-07-27T08:16:08.811818'), ('26.6', '2026-07-27T08:15:57.945373'), ('26.5', '2026-07-27T08:15:47.345203'), ('26.4', '2026-07-27T08:15:35.778523'), ('26.3', '2026-07-27T08:15:22.911945'), ('26.2', '2026-07-27T08:15:10.679094'), ('25.24', '2026-07-27T08:14:51.595427'), ('25.23', '2026-07-27T08:14:40.145534'), ('25.22', '2026-07-27T08:14:30.914454'), ('25.21', '2026-07-27T08:14:19.512344'), ('25.20', '2026-07-27T08:14:09.162382'), ('25.19', '2026-07-27T08:13:58.945762'), ('25.18', '2026-07-27T08:13:47.779488'), ('25.17', '2026-07-27T08:13:36.912473'), ('25.16', '2026-07-27T08:13:25.546330'), ('25.15', '2026-07-27T08:13:15.174096'), ('25.14', '2026-07-27T08:13:07.083372'), ('25.13', '2026-07-27T08:12:58.396828'), ('25.12', '2026-07-27T08:12:49.546385'), ('25.11', '2026-07-27T08:12:37.996659'), ('25.10', '2026-07-27T08:12:28.463268'), ('25.09', '2026-07-27T08:12:18.714919'), ('25.08', '2026-07-27T08:12:10.348688'), ('25.07', '2026-07-27T08:11:59.963309'), ('25.06', '2026-07-27T08:11:50.580233'), ('25.05', '2026-07-27T08:11:37.596991'), ('25.04', '2026-07-27T08:11:25.597461'), ('25', '2026-07-27T08:11:16.613756'), ('14.24', '2026-07-27T08:11:08.397007'), ('14.23', '2026-07-27T08:10:59.417592'), ('14.22', '2026-07-27T08:10:49.863821'), ('14.21', '2026-07-27T08:10:38.920253'), ('14.20', '2026-07-27T08:10:28.447773'), ('14.19', '2026-07-27T08:10:18.780687'), ('14.18', '2026-07-27T08:10:11.680803'), ('14.17', '2026-07-27T08:09:59.431576'), ('14.16', '2026-07-27T08:09:49.680863'), ('14.15', '2026-07-27T08:09:41.936819'), ('14.14', '2026-07-27T08:09:32.683983'), ('14.13', '2026-07-27T08:09:23.815274'), ('14.12', '2026-07-27T08:09:13.330641'), ('14.11', '2026-07-27T08:09:02.363997'), ('14.10', '2026-07-27T08:08:50.669490'), ('14.9', '2026-07-27T08:08:42.981378'), ('14.8', '2026-07-27T08:08:33.450888'), ('14.7', '2026-07-27T08:08:23.868600'), ('14.6', '2026-07-27T08:08:15.548251'), ('14.5', '2026-07-27T08:08:06.501286'), ('14.4', '2026-07-27T08:07:57.499739'), ('14.3', '2026-07-27T08:07:47.798151'), ('14.2', '2026-07-27T08:07:38.498619'), ('14.1', '2026-07-27T08:07:27.048450'), ('13.24', '2026-07-27T08:07:20.341140'), ('13.23', '2026-07-27T08:07:11.515085'), ('13.22', '2026-07-27T08:07:03.667457'), ('13.21', '2026-07-27T08:06:54.948590'), ('13.20', '2026-07-27T08:06:44.415648'), ('13.19', '2026-07-27T08:06:35.700248'), ('13.18', '2026-07-27T08:06:23.734170'), ('13.17', '2026-07-27T08:06:14.448860'), ('13.16', '2026-07-27T08:06:04.533035'), ('13.15', '2026-07-27T08:05:53.567999'), ('13.14', '2026-07-27T08:05:44.209549'), ('13.13', '2026-07-27T08:05:36.215723'), ('13.12', '2026-07-27T08:05:27.749433'), ('13.11', '2026-07-27T08:05:18.465690'), ('13.10', '2026-07-27T08:05:08.665779'), ('13.9', '2026-07-27T08:05:01.014654'), ('13.8', '2026-07-27T08:04:52.772764'), ('13.7', '2026-07-27T08:04:45.199438'), ('13.6', '2026-07-27T08:04:35.499390'), ('13.5', '2026-07-27T08:04:27.738041'), ('13.4', '2026-07-27T08:04:18.666187'), ('13.3', '2026-07-27T08:04:07.783288'), ('13.1', '2026-07-27T08:03:57.599570'), ('12.23', '2026-07-27T08:03:49.168564'), ('12.22', '2026-07-27T08:03:39.137859'), ('12.21', '2026-07-27T08:03:31.435836'), ('12.20', '2026-07-27T08:03:22.741043'), ('12.19', '2026-07-27T08:03:13.739191'), ('12.18', '2026-07-27T08:03:03.367024'), ('12.17', '2026-07-27T08:02:55.183450'), ('12.16', '2026-07-27T08:02:45.000171'), ('12.15', '2026-07-27T08:02:36.384876'), ('12.14', '2026-07-27T08:02:27.946214'), ('12.13', '2026-07-27T08:02:19.266739'), ('12.12', '2026-07-27T08:02:11.951869'), ('12.11', '2026-07-27T08:02:02.785523'), ('12.9', '2026-07-27T08:01:42.768290'), ('12.8', '2026-07-27T08:01:34.816645'), ('12.7', '2026-07-27T08:01:25.100175'), ('12.6', '2026-07-27T08:01:16.566900'), ('12.5', '2026-07-27T08:01:09.435935'), ('12.4', '2026-07-27T08:01:02.166687'), ('12.3', '2026-07-27T08:00:52.866984'), ('12.2', '2026-07-27T08:00:44.985224'), ('12.1', '2026-07-27T08:00:37.200508'), ('11.24', '2026-07-27T08:00:30.349384'), ('11.22', '2026-07-27T08:00:16.695310'), ('11.21', '2026-07-27T08:00:08.150599'), ('11.20', '2026-07-27T08:00:01.017222'), ('11.19', '2026-07-27T07:59:52.169469'), ('11.18', '2026-07-27T07:59:42.500691'), ('11.17', '2026-07-27T07:59:31.934115'), ('11.16', '2026-07-27T07:59:23.434176'), ('11.15', '2026-07-27T07:59:14.351215'), ('11.14', '2026-07-27T07:59:03.167676'), ('11.13', '2026-07-27T07:58:53.501081'), ('11.12', '2026-07-27T07:58:46.935808'), ('11.11', '2026-07-27T07:58:37.051105'), ('11.10', '2026-07-27T07:58:26.884609'), ('11.9', '2026-07-27T07:58:18.901504'), ('11.8', '2026-07-27T07:58:09.151288'), ('11.7', '2026-07-27T07:58:00.901985'), ('11.6', '2026-07-27T07:57:52.123189'), ('11.5', '2026-07-27T07:57:44.935015'), ('11.4', '2026-07-27T07:57:34.818628'), ('11.3', '2026-07-27T07:57:26.892071'), ('11.2', '2026-07-27T07:57:16.601683'), ('11.1', '2026-07-27T07:57:07.568207'), ('10.25', '2026-07-27T07:57:00.387515'), ('10.24', '2026-07-27T07:56:49.218325'), ('10.22', '2026-07-27T07:56:38.086265'), ('10.21', '2026-07-27T07:56:30.052045'), ('10.20', '2026-07-27T07:56:20.068967'), ('10.19', '2026-07-27T07:56:11.852050'), ('10.18', '2026-07-27T07:56:03.152193'), ('10.17', '2026-07-27T07:55:55.152140'), ('10.16', '2026-07-27T07:55:46.635754'), ('10.15', '2026-07-27T07:55:35.218706'), ('10.14', '2026-07-27T07:55:27.042283'), ('10.13', '2026-07-27T07:55:18.935625'), ('10.12', '2026-07-27T07:55:10.718976'), ('10.11', '2026-07-27T07:55:02.668934'), ('10.10', '2026-07-27T07:54:54.686473')]

In [1]:
import transformations.matches as matches

r = matches.upload_soloq_matches(rewrite=True)
print(r)

True

In [4]:
import metadata.metadata as md
import pandas as pd
r = pd.Timestamp(md.get_last_match_date("soloq")) 
print(r)

x = r.strftime('%Y-%m-%d') if pd.notna(r) else pd.Timestamp('1900-01-01').strftime('%Y-%m-%d')
print(x)

2026-07-17 23:24:08
2026-07-17

In [3]:
import transformations.champions as champions

champions.update_champions_dimension()

### Silver Exploration to Remember what I was doing before the hiatus

In [4]:
import pandas as pd
silver_ds_dir = "datasets/silver"

In [5]:
### Checking parquets

champions_changes_df = pd.read_parquet(f"{silver_ds_dir}/champions_changes_dimension.parquet")
#champions_changes_df.head()
# max_patch = champions_changes_df.loc[champions_changes_df['patch_number'] < 2025, ['patch_number']].max()
# print(max_patch)

champions_dimension_df = pd.read_parquet(f"{silver_ds_dir}/champions_dimension.parquet")
#champions_dimension_df.head()

patches_dimension_df = pd.read_parquet(f"{silver_ds_dir}/patches_dimension.parquet")
#patches_dimension_df.head()

In [7]:
pro_matches_ban_list_df = pd.read_parquet(f"{silver_ds_dir}/pro_matches_ban_list.parquet")
#pro_matches_ban_list_df.head()

matches_per_patch = pro_matches_ban_list_df.groupby('patch')['gameid'].nunique()
#print(matches_per_patch)

bans_per_patch = pro_matches_ban_list_df.groupby(['patch', 'ban'])['gameid'].nunique()
#print(bans_per_patch)

ban_rate_df = (
    bans_per_patch
    .div(matches_per_patch, level='patch')
    .reset_index()
    .rename(columns={"gameid": "ban_rate", "ban": "champion"})
)
print(ban_rate_df)
# print(
#     ban_rate_df.
#     loc[ban_rate_df['patch'] >= 15].
#     sort_values(['patch', 'ban_rate'],ascending=False).
#     groupby('patch').head(3))

       patch      champion  ban_rate
0      10.01        Aatrox  0.104000
1      10.01         Akali  0.884000
2      10.01         Amumu  0.004000
3      10.01      Aphelios  0.456000
4      10.01  Aurelion Sol  0.020000
...      ...           ...       ...
25518   9.24         Vayne  0.021739
25519   9.24         Xayah  0.152174
25520   9.24         Yasuo  0.086957
25521   9.24         Yuumi  0.043478
25522   9.24           Zoe  0.065217

[25523 rows x 3 columns]

In [8]:
pro_matches_summary_df = pd.read_parquet(f"{silver_ds_dir}/pro_matches_summary.parquet")
#print(pro_matches_summary_df.head())
#pro_matches_summary_df.columns

patches_stats = (
    pro_matches_summary_df
    .groupby('patch')
    .agg(
        matches=('gameid', 'nunique'),
        players=('playername', 'nunique'),
        champions=('champion', 'nunique'),
        avg_gamelength=('gamelength', 'mean'),
        avg_player_kills=('kills', 'mean'),
        avg_player_deaths=('deaths', 'mean'),
        avg_player_assists=('assists', 'mean')
    )
    .assign(
        match_type='professional'
    )
    .reset_index()
)
#print(patches_stats)

matches_per_patch = pro_matches_summary_df.groupby('patch')['gameid'].nunique()

pick_per_patch = pro_matches_summary_df.groupby(['patch', 'champion'])['gameid'].nunique()
#print(picked_per_patch)

pick_rate = (
    pick_per_patch
    .div(matches_per_patch, level='patch')
    .rename('pick_rate')
    .reset_index()
) 
#print(pick_rate)

# champions_stats = (
#     pick_rate
#     .merge(ban_rate_df, on=['patch', 'champion'])
# )
# #print(champions_stats.loc[champions_stats['champion'] == 'Jinx'])

top_pick_per_patch = (
    pick_rate
    .loc[pick_rate.groupby('patch')['pick_rate'].idxmax()]
    .rename(columns={"champion": "top_pick_champion", "pick_rate": "top_pick_rate"})
    .reset_index(drop=True)
)

top_ban_per_patch = (
    ban_rate_df
    .loc[ban_rate_df.groupby('patch')['ban_rate'].idxmax()]
    .rename(columns={"champion": "top_ban_champion", "ban_rate": "top_ban_rate"})
    .reset_index(drop=True)
)
# print(top_pick_per_patch)
# print(top_ban_per_patch)

top_champions_stats = (
    top_pick_per_patch
    .merge(top_ban_per_patch, on='patch')
)


pro_patches_stats = (
    patches_stats
    .merge(top_champions_stats, on='patch')
)
print(pro_patches_stats.head())

# print('Min patch in 1: ', patches_stats['patch'].min(), 'Max patch in 1: ', patches_stats['patch'].max())
# print('Min patch in 2: ', patches_stats2['patch'].min(), 'Max patch in 2: ', patches_stats2['patch'].max())
# print('Min patch in banlist: ', ban_rate_df['patch'].min(), 'Max patch in banlist: ', ban_rate_df['patch'].max())
# print('Min patch in picklist: ', pick_rate['patch'].min(), 'Max patch in picklist: ', pick_rate['patch'].max())
# print('Min patch in top champions: ', top_champions_stats['patch'].min(), 'Max patch in top champions: ', top_champions_stats['patch'].max())

   patch  matches  players  champions  avg_gamelength  avg_player_kills  \
0  10.01      250      916        113     1977.172000          2.748400
1  10.02      559     1270        132     2007.255814          2.694454
2  10.03      570     1363        136     1968.061404          2.659649
3  10.04      624     1504        137     1984.044872          2.700962
4  10.05      546     1222        127     1936.261905          2.669414

   avg_player_deaths  avg_player_assists    match_type top_pick_champion  \
0           2.752000            6.134800  professional             Braum
1           2.698569            6.070125  professional          Aphelios
2           2.664737            5.998421  professional      Miss Fortune
3           2.707212            6.012019  professional      Miss Fortune
4           2.672527            6.081868  professional          Nautilus

   top_pick_rate top_ban_champion  top_ban_rate
0       0.560000            Akali      0.884000
1       0.518784            Akali      0.871199
2       0.482456         Aphelios      0.555360
3       0.448718             Ornn      0.730769
4       0.401099            Senna      0.642857

In [15]:
##Reload pro_matches_summary silver dataset
import pandas as pd
from transformations.matches import process_oe_match_summary
from transformations.utils import BRONZE_DATASETS_DIR, PRO_MATCHES_SUMMARY_FILE

years = [2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026]

for year in years:
    source_file_dir = BRONZE_DATASETS_DIR / 'oe' / f'{year}_LoL_esports_match_data_from_OraclesElixir.csv'
    oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})
    matches_summary_df = process_oe_match_summary(oe_df, True if year == 2014 else False)
    try:
        matches_summary_df.to_parquet(PRO_MATCHES_SUMMARY_FILE, engine='pyarrow', index=False)
        print(f"Year {year} processed successfully.")
    except Exception as e:
        raise ValueError(f"Failed to write the matches summary DataFrame to Parquet format for year {year}. Error: {e}")

Year 2014 processed successfully.
Year 2015 processed successfully.
Year 2016 processed successfully.

C:\Users\Feragon\AppData\Local\Temp\ipykernel_29124\4212471342.py:10: DtypeWarning: Columns (0: pick1, 1: pick2, 2: pick3, 3: pick4, 4: pick5) have mixed types. Specify dtype option on import or set low_memory=False.
  oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})

Year 2017 processed successfully.
Year 2018 processed successfully.
Year 2019 processed successfully.
Year 2020 processed successfully.
Year 2021 processed successfully.

C:\Users\Feragon\AppData\Local\Temp\ipykernel_29124\4212471342.py:10: DtypeWarning: Columns (0: url) have mixed types. Specify dtype option on import or set low_memory=False.
  oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})

Year 2022 processed successfully.

C:\Users\Feragon\AppData\Local\Temp\ipykernel_29124\4212471342.py:10: DtypeWarning: Columns (0: url) have mixed types. Specify dtype option on import or set low_memory=False.
  oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})

Year 2023 processed successfully.

C:\Users\Feragon\AppData\Local\Temp\ipykernel_29124\4212471342.py:10: DtypeWarning: Columns (0: url) have mixed types. Specify dtype option on import or set low_memory=False.
  oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})

Year 2024 processed successfully.

C:\Users\Feragon\AppData\Local\Temp\ipykernel_29124\4212471342.py:10: DtypeWarning: Columns (0: url, 1: split) have mixed types. Specify dtype option on import or set low_memory=False.
  oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})

Year 2025 processed successfully.

C:\Users\Feragon\AppData\Local\Temp\ipykernel_29124\4212471342.py:10: DtypeWarning: Columns (0: url) have mixed types. Specify dtype option on import or set low_memory=False.
  oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})

Year 2026 processed successfully.

In [ ]:
##Reload pro_matches_ban silver dataset

import pandas as pd
from transformations.matches import process_oe_ban_list
from transformations.utils import BRONZE_DATASETS_DIR, PRO_MATCHES_BAN_LIST_FILE

years = [2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026]

for year in years:
    source_file_dir = BRONZE_DATASETS_DIR / 'oe' / f'{year}_LoL_esports_match_data_from_OraclesElixir.csv'
    oe_df = pd.read_csv(source_file_dir, dtype={'patch': str})
    ban_list_df = process_oe_ban_list(oe_df, True if year == 2014 else False)
    try:
        ban_list_df.to_parquet(PRO_MATCHES_BAN_LIST_FILE, engine='pyarrow', index=False)
        print(f"Year {year} processed successfully.")
    except Exception as e:
        raise ValueError(f"Failed to write the matches summary DataFrame to Parquet format for year {year}. Error: {e}")

In [11]:
soloq_matches_ban_list = pd.read_parquet(f"{silver_ds_dir}/soloq_matches_ban_list.parquet")
#print(soloq_matches_ban_list.head())

ban_rate_df = (
    soloq_matches_ban_list
    .groupby(['patch', 'ban'])
    .agg(
        ban_amt=('gameid', 'nunique')
    )
    .reset_index()
    .assign(
        ban_rate=lambda x: x['ban_amt'] / x['patch'].map(patches_stats.set_index('patch')['matches']),
        champion_real_name = lambda x: x['ban'].map(champions_dimension_df.set_index('champion')['champion_real_name']),
    )
    .rename(columns={"champion_real_name": "champion"})
    .drop(columns=['ban'])
)
#print(ban_rate_df.head())

top_ban_rate_df = (
    ban_rate_df
    .loc[ban_rate_df.groupby('patch')['ban_rate'].idxmax()]
    .rename(columns={"ban_rate": "top_ban_rate", "champion": "top_ban_champion"})
    .reset_index(drop=True)
)
print(top_ban_rate_df.head())

   patch  ban_amt  top_ban_rate top_ban_champion
0  14.14        4      0.800000           Aurora
1  14.15       58      0.542056           Aurora
2  14.16       52      0.590909           Aurora
3  14.17       24      0.387097           Aurora
4  14.18       24      0.489796             Hwei

In [12]:
soloq_matches_summary_df = pd.read_parquet(f"{silver_ds_dir}/soloq_matches_summary.parquet")
#print(soloq_matches_summary_df.head())

#print('Max patch is ', soloq_matches_summary_df['patch'].max(), ' min ', soloq_matches_summary_df['patch'].min())

patches_stats = (
    soloq_matches_summary_df
    .groupby('patch')
    .agg(
        matches=('match_id', 'nunique'),
        # players=('playername', 'nunique'),
        champions=('champion', 'nunique'),
        avg_gamelength=('gamelength', 'mean'),
        avg_player_kills=('kills', 'mean'),
        avg_player_deaths=('deaths', 'mean'),
        avg_player_assists=('assists', 'mean')
    )
    .assign(
        match_type='soloq'
    )
    .reset_index()
)
#print(patches_stats.head())
#print(patches_stats.loc[patches_stats['patch']=='14.14'])

pick_rate_df = (
    soloq_matches_summary_df
    .groupby(['patch', 'champion'])
    .agg(
        pick_amt=('match_id', 'nunique')
    )
    .reset_index()
    .assign(
        pick_rate=lambda x: x['pick_amt'] / x['patch'].map(patches_stats.set_index('patch')['matches']),
        champion_real_name = lambda x: x['champion'].map(champions_dimension_df.set_index('champion')['champion_real_name'])
    )
    .drop(columns=['champion'])
    .rename(columns={"champion_real_name": "champion"})
    .reset_index(drop=True)
)
#print(pick_rate_df.head())

top_pick_rate_df = (
    pick_rate_df
    .loc[pick_rate_df.groupby('patch')['pick_rate'].idxmax()]
    .rename(columns={"pick_rate": "top_pick_rate", "champion": "top_pick_champion"})
    .reset_index(drop=True)
)
#print(top_pick_rate_df.head())

soloq_patches_stats = (
    patches_stats
    .merge(top_pick_rate_df, on='patch')
    .merge(top_ban_rate_df, on='patch')
)
print(soloq_patches_stats.head(10))

   patch  matches  champions         avg_gamelength  avg_player_kills  \
0  14.14        5         40 0 days 00:25:10.800000          4.680000
1  14.15      107        162 0 days 00:25:45.327102          5.019626
2  14.16       88        161 0 days 00:27:54.318181          5.401136
3  14.17       62        149 0 days 00:26:19.580645          5.277419
4  14.18       49        147 0 days 00:27:43.387755          5.100000
5  14.19       58        151 0 days 00:26:17.379310          5.074138
6  14.20      198        168 0 days 00:26:58.338383          5.297475
7  14.21       85        159 0 days 00:26:39.529411          5.264706
8  14.22       73        151 0 days 00:27:43.328767          5.326027
9  14.23      196        169 0 days 00:28:24.025510          5.653061

   avg_player_deaths  avg_player_assists match_type  pick_amt  top_pick_rate  \
0           4.720000            6.220000      soloq         3       0.600000
1           5.028037            7.529907      soloq        27       0.252336
2           5.415909            7.637500      soloq        33       0.375000
3           5.295161            7.225806      soloq        15       0.241935
4           5.112245            7.046939      soloq        15       0.306122
5           5.091379            7.534483      soloq        23       0.396552
6           5.315657            7.626263      soloq        60       0.303030
7           5.287059            7.443529      soloq        22       0.258824
8           5.350685            7.491781      soloq        22       0.301370
9           5.668878            8.046939      soloq        50       0.255102

  top_pick_champion  ban_amt  top_ban_rate top_ban_champion
0            Ezreal        4      0.800000           Aurora
1            Kai'Sa       58      0.542056           Aurora
2            Wukong       52      0.590909           Aurora
3            Kai'Sa       24      0.387097           Aurora
4              Jhin       24      0.489796             Hwei
5            Kai'Sa       38      0.655172             Udyr
6            Kai'Sa       65      0.328283             Pyke
7            Zilean       41      0.482353             Pyke
8           Caitlyn       39      0.534247          Ambessa
9             Viego      110      0.561224          Ambessa

In [3]:
import pandas as pd
silver_ds_dir = "datasets/silver"

champions_dimension_df = pd.read_parquet(f"{silver_ds_dir}/champions_dimension.parquet")
# print(champions_dimension_df.head())
#print(champions_dimension_df.loc[champions_dimension_df['champion'].str.contains("'")])
# print(pick_rate.loc[pick_rate['champion'].str.contains("'")]['champion'].unique())

print(champions_dimension_df.loc[champions_dimension_df['champion'].isin(["Khazix", "Kogmaw", "Velkoz", "Reksai", "Chogath", "Kaisa", "Belveth", "Ksante", "MonkeyKing"])])

#print(champions_dimension_df.loc[champions_dimension_df['champion'].str.contains("KS")])

       champion  champion_id champion_real_name
3         Kaisa          145             Kai'Sa
12       Velkoz          161            Vel'Koz
65   MonkeyKing           62             Wukong
132      Khazix          121            Kha'Zix
134     Belveth          200           Bel'Veth
159     Chogath           31           Cho'Gath

In [1]:
from transformations.champions import update_champions_dimension
update_champions_dimension()

In [13]:

### Champions
import pandas as pd
silver_ds_dir = "datasets/silver"
pro_matches_summary_df = pd.read_parquet(f"{silver_ds_dir}/pro_matches_summary.parquet")
# #print(pro_matches_summary_df.head(10))
# #pro_matches_summary_df.columns
#print(pro_matches_summary_df['patch'].unique())

pro_matches_ban_list = pd.read_parquet(f"{silver_ds_dir}/pro_matches_ban_list.parquet")
#print(pro_matches_ban_list['patch'].unique())

pro_pick_rate_df = (
    pro_matches_summary_df
    .groupby(['patch', 'champion'])
    .agg(
        pick_amt=('gameid', 'nunique')
    )
    .reset_index()
    .assign(
        pick_rate=lambda x: x['pick_amt'] / x['patch'].map(pro_patches_stats.set_index('patch')['matches']),
        champion_real_name = lambda x: x['champion'].map(champions_dimension_df.set_index('champion')['champion_real_name'])
    )
    .drop(columns=['champion'])
    .rename(columns={"champion_real_name": "champion"})
    .reset_index(drop=True)
)
#print(pro_pick_rate_df.head(10))

pro_ban_rate_df = (
    pro_matches_ban_list
    .groupby(['patch', 'ban'])
    .agg(
        ban_amt=('gameid', 'nunique')
    )
    .reset_index()
    .assign(
        ban_rate=lambda x: x['ban_amt'] / x['patch'].map(pro_patches_stats.set_index('patch')['matches']),
        champion_real_name = lambda x: x['ban'].map(champions_dimension_df.set_index('champion')['champion_real_name']),
    )
    .rename(columns={"champion_real_name": "champion"})
    .drop(columns=['ban'])
)
#print(pro_ban_rate_df.head(10))

soloq_matches_summary_df = pd.read_parquet(f"{silver_ds_dir}/soloq_matches_summary.parquet")
soloq_matches_ban_list = pd.read_parquet(f"{silver_ds_dir}/soloq_matches_ban_list.parquet")

soloq_pick_rate_df = (
    soloq_matches_summary_df
    .groupby(['patch', 'champion'])
    .agg(
        pick_amt=('match_id', 'nunique')
    )
    .reset_index()
    .assign(
        pick_rate=lambda x: x['pick_amt'] / x['patch'].map(soloq_patches_stats.set_index('patch')['matches']),
        champion_real_name = lambda x: x['champion'].map(champions_dimension_df.set_index('champion')['champion_real_name'])
    )
    .drop(columns=['champion'])
    .rename(columns={"champion_real_name": "champion"})
    .reset_index(drop=True)
)
# soloq_pick_rate_df.columns

soloq_ban_rate_df = (
    soloq_matches_ban_list
    .groupby(['patch', 'ban'])
    .agg(
        ban_amt=('gameid', 'nunique')
    )
    .reset_index()
    .assign(
        ban_rate=lambda x: x['ban_amt'] / x['patch'].map(soloq_patches_stats.set_index('patch')['matches']),
        champion_real_name = lambda x: x['ban'].map(champions_dimension_df.set_index('champion')['champion_real_name']),
    )
    .rename(columns={"champion_real_name": "champion"})
    .drop(columns=['ban'])
)
# soloq_ban_rate_df.columns

In [23]:
from transformations.patches import upload_patches_dimension, upload_champions_changes_dimension

upload_patches_dimension(rewrite=True)
upload_champions_changes_dimension(rewrite=True)

champions_changes_dimension_df = (
    pd.read_parquet(f"{silver_ds_dir}/champions_changes_dimension.parquet")
    .rename(columns={"patch_number": "patch", "champion_name": "champion"})
)
#print(champions_changes_dimension_df.head())
#print(champions_changes_dimension_df['patch_number'].unique())
print(champions_changes_dimension_df.loc[champions_changes_dimension_df['champion'] == "K'Sante"])

      patch champion change_type
813   12.23  K'Sante        Buff
837    13.3  K'Sante        Nerf
945   13.12  K'Sante        Nerf
1072  13.21  K'Sante        Buff
1080  13.22  K'Sante        Nerf
1090  13.23  K'Sante        Nerf
1104  13.24  K'Sante        Buff
1245  14.10  K'Sante        Buff
1433  14.22  K'Sante        Nerf
1517  25.05  K'Sante        Nerf
1578  25.09  K'Sante        Buff
1933  26.13  K'Sante        Nerf

In [32]:
champion_info_pro = (
    pro_matches_summary_df
    .groupby(['patch','champion'])
    .agg(
        avg_gamelength=('gamelength', 'mean'),
        avg_kills=('kills', 'mean'),
        avg_deaths=('deaths', 'mean'),
        avg_assists=('assists', 'mean'),
        total_kills=('kills', 'sum'),
        total_deaths=('deaths', 'sum'),
        total_assists=('assists', 'sum'),
        avg_doublekills=('doublekills', 'mean'),
        avg_triplekills=('triplekills', 'mean'),
        avg_quadrakills=('quadrakills', 'mean'),
        avg_pentakills=('pentakills', 'mean'),
        total_doublekills=('doublekills', 'sum'),
        total_triplekills=('triplekills', 'sum'),
        total_quadrakills=('quadrakills', 'sum'),
        total_pentakills=('pentakills', 'sum'),
    )
    .reset_index()
    .assign(
        match_type = 'pro',
        avg_kda=lambda x: (x['avg_kills'] + x['avg_assists']) / x['avg_deaths'].replace(0, 1),
        total_kda=lambda x: (x['total_kills'] + x['total_assists']) / x['total_deaths'].replace(0, 1),
        champion_real_name = lambda x: x['champion'].map(champions_dimension_df.set_index('champion')['champion_real_name'])
    )
    .drop(columns=['champion'])
    .rename(columns={"champion_real_name": "champion"})
    .merge(pro_pick_rate_df, on=['patch', 'champion'], how='left')
    .merge(pro_ban_rate_df, on=['patch', 'champion'], how='left')
    .merge(champions_changes_dimension_df, on=['patch', 'champion'], how='left')
    .fillna({**{col: 0 for col in ['pick_amt', 'ban_amt', 'pick_rate', 'ban_rate']}, 'change_type': 'None'})
    .pipe(lambda d: d[['match_type','patch', 'champion', *d.columns.difference(['match_type','patch', 'champion'], sort=False)]])
)
champion_info_pro.loc[champion_info_pro['change_type'] != 'None'].head(10)

,match_type,patch,champion,avg_gamelength,avg_kills,avg_deaths,avg_assists,total_kills,total_deaths,total_assists,...,total_triplekills,total_quadrakills,total_pentakills,avg_kda,total_kda,pick_amt,pick_rate,ban_amt,ban_rate,change_type
35811,pro,10.10,Diana,1586.500000,1.000000,5.500000,2.000000,2,11,4,...,0.0,0.0,0.0,0.545455,0.545455,2,0.012579,4.0,0.025157,Nerf
36064,pro,10.10,Irelia,2030.400000,5.300000,2.200000,5.600000,53,22,56,...,2.0,1.0,1.0,4.954545,4.954545,10,0.062893,18.0,0.113208,Buff
36554,pro,10.10,Katarina,2088.000000,5.000000,8.000000,3.000000,5,8,3,...,0.0,0.0,0.0,1.000000,1.000000,1,0.006289,0.0,0.000000,Nerf
36556,pro,10.10,Kayn,2033.500000,2.000000,6.000000,4.500000,4,12,9,...,0.0,0.0,0.0,1.083333,1.083333,2,0.012579,0.0,0.000000,Nerf
36799,pro,10.10,Kled,1631.500000,3.500000,2.000000,4.750000,14,8,19,...,0.0,0.0,0.0,4.125000,4.125000,4,0.025157,9.0,0.056604,Nerf
37527,pro,10.10,Maokai,1922.894737,1.736842,3.526316,6.684211,33,67,127,...,0.0,0.0,0.0,2.388060,2.388060,19,0.119497,9.0,0.056604,Nerf
37771,pro,10.10,Nidalee,1881.050000,3.600000,3.000000,5.750000,72,60,115,...,0.0,0.0,0.0,3.116667,3.116667,20,0.125786,23.0,0.144654,Buff
38030,pro,10.10,Sivir,1790.250000,4.500000,2.500000,3.500000,18,10,14,...,0.0,0.0,0.0,3.200000,3.200000,4,0.025157,0.0,0.000000,Buff
38032,pro,10.10,Soraka,2021.500000,0.333333,2.500000,10.083333,4,30,121,...,0.0,0.0,0.0,4.166667,4.166667,12,0.075472,15.0,0.094340,Buff
38276,pro,10.10,Taric,1829.545455,0.363636,2.818182,9.636364,4,31,106,...,0.0,0.0,0.0,3.548387,3.548387,11,0.069182,8.0,0.050314,Nerf

In [1]:
champion_info_soloq = (
    soloq_matches_summary_df
    .groupby(['patch','champion'])
    .agg(
        avg_gamelength=('gamelength', 'mean'),
        avg_kills=('kills', 'mean'),
        avg_deaths=('deaths', 'mean'),
        avg_assists=('assists', 'mean'),
        total_kills=('kills', 'sum'),
        total_deaths=('deaths', 'sum'),
        total_assists=('assists', 'sum'),
        avg_doublekills=('doublekills', 'mean'),
        avg_triplekills=('triplekills', 'mean'),
        avg_quadrakills=('quadrakills', 'mean'),
        avg_pentakills=('pentakills', 'mean'),
        total_doublekills=('doublekills', 'sum'),
        total_triplekills=('triplekills', 'sum'),
        total_quadrakills=('quadrakills', 'sum'),
        total_pentakills=('pentakills', 'sum'),
    )
    .reset_index()
    .assign(
        match_type = 'soloq',
        avg_kda=lambda x: (x['avg_kills'] + x['avg_assists']) / x['avg_deaths'].replace(0, 1),
        total_kda=lambda x: (x['total_kills'] + x['total_assists']) / x['total_deaths'].replace(0, 1),
        champion_real_name = lambda x: x['champion'].map(champions_dimension_df.set_index('champion')['champion_real_name'])
    )
    .drop(columns=['champion'])
    .rename(columns={"champion_real_name": "champion"})
    .merge(soloq_pick_rate_df, on=['patch', 'champion'], how='left')
    .merge(soloq_ban_rate_df, on=['patch', 'champion'], how='left')
    .merge(champions_changes_dimension_df, on=['patch', 'champion'], how='left')
    .fillna({**{col: 0 for col in ['pick_amt', 'ban_amt', 'pick_rate', 'ban_rate']}, 'change_type': 'None'})
    .pipe(lambda d: d[['match_type','patch', 'champion', *d.columns.difference(['match_type','patch', 'champion'], sort=False)]])
)
#print(champion_info_soloq.head(20))
champion_info_soloq.loc[champion_info_soloq['change_type'] != 'None'].head(10)

NameError: name 'soloq_matches_summary_df' is not defined

### Gold layer ideas during silver exploration
* A Table with basic stats per patch
    * Amount of matches, diff players, diff champions, diff ban champions
    * Top and less banned champion, picked champion
    * Avg KDA
    * A flag to identify between profesional and soloq
* A table with pick and ban info per patch
* A table with champions stats per patch:
    * Ban and pick rate / amt
    * KDA avg and total
    * Kill streaks avg and total
    * Patch buff and nerf flags

In [11]:
from transformations.patches import build_champions_changes_gold
from transformations.utils import CHAMPIONS_CHANGES_GOLD
import pandas as pd
x=build_champions_changes_gold()
print(x)

df = pd.read_parquet(CHAMPIONS_CHANGES_GOLD, engine='pyarrow')
df.head(10)

print(df['patch'].min())
print(df['patch'].max())
print(df.loc[df['champion']=="K'Sante"])
print(df.loc[df['patch']=="26.8"])
print(df['patch'].unique())

True
10.10
26.9
      patch champion change_type
813   12.23  K'Sante        Buff
837    13.3  K'Sante        Nerf
945   13.12  K'Sante        Nerf
1072  13.21  K'Sante        Buff
1080  13.22  K'Sante        Nerf
1090  13.23  K'Sante        Nerf
1104  13.24  K'Sante        Buff
1245  14.10  K'Sante        Buff
1433  14.22  K'Sante        Nerf
1517  25.05  K'Sante        Nerf
1578  25.09  K'Sante        Buff
1933  26.13  K'Sante        Nerf
     patch   champion change_type
1887  26.8  Dr. Mundo        Nerf
1888  26.8      Karma        Nerf
1889  26.8        Mel        Nerf
1890  26.8       Hwei        Buff
1891  26.8     Lillia        Buff
1892  26.8     Lucian        Buff
<ArrowStringArray>
['10.10', '10.11', '10.12', '10.13', '10.14', '10.15', '10.16', '10.17',
 '10.18', '10.19',
 ...
  '26.7',  '26.8',  '26.9', '26.10', '26.11', '26.12', '26.13', '26.14',
 '26.15', '26.16']
Length: 144, dtype: str

In [17]:
from transformations.champions import build_ban_list_gold
from transformations.utils import CHAMPIONS_PICK_STATS_FILE, PRO_MATCHES_SUMMARY_FILE, SILVER_DATASETS_DIR
import pandas as pd

x = build_ban_list_gold()
print(x)

df = pd.read_parquet(CHAMPIONS_PICK_STATS_FILE)
#df.head(20)
print(df['patch'].min())
print(df['patch'].max())

df.loc[df['patch'] == '26.8']
#df.loc[df['champion'] == "K'Sante"]

None
10.01
9.24

,patch,champion,pro_pick_amt,pro_pick_rate,pro_ban_amt,pro_ban_rate,soloq_pick_amt,soloq_pick_rate,soloq_ban_amt,soloq_ban_rate
26252,26.8,Dr. Mundo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26253,26.8,Hwei,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26254,26.8,Karma,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26255,26.8,Lillia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26256,26.8,Lucian,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26257,26.8,Mel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df=pd.read_parquet(PRO_MATCHES_SUMMARY_FILE)
df.loc[df['patch'].str.contains('25.')] ##I have no pro matches from 2025??? Check this

,gameid,date,patch,side,position,playername,champion,gamelength,result,kills,...,opp_csat20,killsat25,assistsat25,deathsat25,csat25,opp_killsat25,opp_assistsat25,opp_deathsat25,opp_csat25,total_cs
730090,LOLTMNT99_132542,2024-01-05 14:08:39,14.01,Blue,top,Taegyeong,Renekton,1446,1,4,...,191.0,4.0,4.0,1.0,210.0,1.0,1.0,3.0,207.0,210.0
730091,LOLTMNT99_132542,2024-01-05 14:08:39,14.01,Blue,jng,CHEF,Xin Zhao,1446,1,5,...,138.0,5.0,11.0,1.0,154.0,2.0,3.0,2.0,154.0,154.0
730092,LOLTMNT99_132542,2024-01-05 14:08:39,14.01,Blue,mid,Nakyung,LeBlanc,1446,1,1,...,160.0,1.0,8.0,3.0,208.0,1.0,4.0,3.0,190.0,208.0
730093,LOLTMNT99_132542,2024-01-05 14:08:39,14.01,Blue,bot,Ruep,Varus,1446,1,8,...,149.0,8.0,7.0,1.0,234.0,1.0,4.0,5.0,170.0,234.0
730094,LOLTMNT99_132542,2024-01-05 14:08:39,14.01,Blue,sup,Carry,Renata Glasc,1446,1,2,...,30.0,2.0,17.0,1.0,25.0,2.0,2.0,7.0,31.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831855,LOLTMNT02_194401,2024-12-08 09:03:13,14.23,Red,top,Morgan,Jax,2546,1,7,...,175.0,4.0,0.0,1.0,193.0,1.0,2.0,3.0,232.0,332.0
831856,LOLTMNT02_194401,2024-12-08 09:03:13,14.23,Red,jng,HamBak,Sejuani,2546,1,2,...,162.0,2.0,3.0,3.0,127.0,2.0,3.0,0.0,201.0,174.0
831857,LOLTMNT02_194401,2024-12-08 09:03:13,14.23,Red,mid,Clozer,Azir,2546,1,2,...,179.0,0.0,2.0,2.0,247.0,4.0,1.0,2.0,211.0,395.0
831858,LOLTMNT02_194401,2024-12-08 09:03:13,14.23,Red,bot,Hype,Jhin,2546,1,6,...,207.0,1.0,0.0,0.0,250.0,1.0,5.0,0.0,253.0,415.0
831859,LOLTMNT02_194401,2024-12-08 09:03:13,14.23,Red,sup,Pollu,Rell,2546,1,1,...,34.0,0.0,4.0,2.0,30.0,0.0,5.0,2.0,35.0,33.0